[package]
name = "exporter"
version = "0.1.0"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
futures = "0.3"
ruffle_core = { path = "../core", features = ["deterministic"] }
ruffle_render_wgpu = { path = "../render/wgpu", features = ["clap"] }
image = "0.24.5"
log = "0.4"
walkdir = "2.3.2"
indicatif = "0.17"
anyhow = "1.0"
rayon = "1.6.0"

[features]
avm_debug = ["ruffle_core/avm_debug"]
render_debug_labels = ["ruffle_render_wgpu/render_debug_labels"]
render_trace = ["ruffle_render_wgpu/render_trace"]
lzma = ["ruffle_core/lzma"]
