[package]
name = "ruffle_render_canvas"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.60"
log = "0.4"
ruffle_web_common = { path = "../../web/common" }
wasm-bindgen = "=0.2.83"
fnv = "1.0.7"
ruffle_render = { path = "..", features = ["web"] }
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
swf = { path = "../../swf" }

[dependencies.web-sys]
version = "0.3.60"
features = [
    "CanvasGradient", "CanvasPattern", "CanvasRenderingContext2d", "CanvasWindingRule", "CssStyleDeclaration",
    "Document", "DomMatrix", "Element", "HtmlCanvasElement", "ImageData", "Navigator", "Path2d", "SvgMatrix",
]
