[package]
name = "ruffle_video_external"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ruffle_render = { path = "../../render" }
ruffle_video = { path = ".." }
swf = { path = "../../swf" }
slotmap = { workspace = true }
tracing = { workspace = true }
ruffle_video_software = { path = "../software" }

# Needed for OpenH264:
libloading = "0.8.5"
reqwest = { version = "0.12.5", default-features = false, features = ["blocking"] }
hex = "0.4.3"
bzip2 = { version = "0.4.4", features = ["static"] }
tempfile = "3.12.0"
sha2 = "0.10.8"
