[package]
name = "ruffle_core"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
byteorder = "1.4"
bitstream-io = "1.6.0"
flate2 = "1.0.24"
fnv = "1.0.7"
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
generational-arena = "0.2.8"
indexmap = "1.9.2"
log = "0.4"
minimp3 = { version = "0.5.1", optional = true }
ruffle_render = { path = "../render" }
ruffle_video = { path = "../video" }
ruffle_macros = { path = "macros" }
ruffle_wstr = { path = "../wstr" }
swf = { path = "../swf" }
bitflags = "1.3.2"
smallvec = { version = "1.10.0", features = ["union"] }
num-traits = "0.2"
num-derive = "0.3"
quick-xml = { git = "https://github.com/ruffle-rs/quick-xml", rev = "8496365ec1412eb5ba5de350937b6bce352fa0ba" }
downcast-rs = "1.2.0"
url = "2.3.1"
weak-table = "0.3.2"
percent-encoding = "2.2.0"
thiserror = "1.0"
chrono = "0.4"
instant = "0.1"
encoding_rs = "0.8.31"
rand = { version = "0.8.5", features = ["std", "small_rng"], default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
nellymoser-rs = { git = "https://github.com/ruffle-rs/nellymoser", rev = "4a33521c29a918950df8ae9fe07e527ac65553f5", optional = true }
regress = "0.4"
flash-lso = { git = "https://github.com/ruffle-rs/rust-flash-lso", rev = "19fecd07b9888c4bdaa66771c468095783b52bed" }
lzma-rs = {version = "0.2.0", optional = true }
dasp = { git = "https://github.com/RustAudio/dasp", rev = "f05a703", features = ["interpolate", "interpolate-linear", "signal"], optional = true }
symphonia = { version = "0.5.1", default-features = false, features = ["mp3"], optional = true }
enumset = "1.0.12"
static_assertions = "1.1.0"
rustversion = "1.0.9"
bytemuck = "1.12.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.25"

[target.'cfg(target_family = "wasm")'.dependencies.wasm-bindgen-futures]
version = "0.4.33"

[features]
default = []
lzma = ["lzma-rs", "swf/lzma"]
wasm-bindgen = [ "instant/wasm-bindgen" ]
avm_debug = []
deterministic = []
timeline_debug = []
nellymoser = ["nellymoser-rs"]
audio = ["dasp"]

[build-dependencies]
build_playerglobal = { path = "build_playerglobal" }
