[package]
name = "ruffle_render_webgl"
version = "0.1.0"
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3.60"
log = "0.4"
ruffle_web_common = { path = "../../web/common" }
ruffle_render = { path = "..", features = ["tessellator", "web"] }
wasm-bindgen = "=0.2.83"
bytemuck = { version = "1.12.3", features = ["derive"] }
gc-arena = { git = "https://github.com/ruffle-rs/gc-arena" }
fnv = "1.0.7"
swf = { path = "../../swf" }
thiserror = "1.0"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "HtmlCanvasElement", "OesVertexArrayObject", "WebGl2RenderingContext", "WebGlBuffer", "WebglDebugRendererInfo",
    "WebGlFramebuffer", "WebGlProgram", "WebGlRenderbuffer", "WebGlRenderingContext", "WebGlShader", "WebGlTexture",
    "WebGlUniformLocation", "WebGlVertexArrayObject",
]
