[package]
name = "naga-agal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
naga = { version = "0.10.0" }
num-derive = "0.3.3"
num-traits = "0.2.15"

[dev-dependencies]
insta = "1.21.2"
naga = { version = "0.10.0", features = ["wgsl-out", "validate"] }
