name: Test Web

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  changes:
    name: Paths filter
    runs-on: ubuntu-22.04
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '!**.md'

  build:
    needs: changes
    if: needs.changes.outputs.src == 'true'
    name: Test Node.js ${{ matrix.node_version }} / Rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ["18", "19"]
        rust_version: [stable] # We most likely don't care about Rust versions here, we'll catch those issues in test_rust.yml.
        os: [ubuntu-22.04, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
          targets: wasm32-unknown-unknown

      - name: Cache Cargo output
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "web"

      # wasm-bindgen-cli version must match wasm-bindgen crate version.
      # Be sure to update in release_nightly.yml, web/Cargo.toml and web/README.md.
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --version 0.2.83

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: binaryen

      # conda is available only with "shell: bash -l {0}".
      # See https://github.com/marketplace/actions/setup-miniconda.
      - name: Install binaryen
        shell: bash -l {0}
        run: conda install -c conda-forge binaryen

      - name: Build
        env:
          # Verify that all features build.
          CARGO_FLAGS: --locked --all-features
        working-directory: web
        shell: bash -l {0}
        run: |
          npm ci
          npm run build

      - name: Check formatting
        working-directory: web
        run: npm run lint

      - name: Run tests
        # MIKE: Don't run web tests on Windows because it's flaky for unknown reasons. :-(
        if: runner.os == 'Linux'
        working-directory: web
        run: npm test

  check-required:
    needs: changes
    if: needs.changes.outputs.src == 'false'
    name: Test Node.js ${{ matrix.node_version }} / Rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ["18", "19"]
        rust_version: [stable] # We most likely don't care about Rust versions here, we'll catch those issues in test_rust.yml.
        os: [ubuntu-22.04, windows-latest]

    steps:
      - name: No-op
        run: echo noop
