[package]
name = "ruffle_web"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "Web (WASM) bindings to the Ruffle flash player"
readme = "README.md"
homepage = "https://ruffle.rs"
repository = "https://github.com/ruffle-rs/ruffle/"
publish = false # This crate is useless alone, people should use the npm package

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["canvas", "console_error_panic_hook", "console_log", "webgl"]

# core features
avm_debug = ["ruffle_core/avm_debug"]
lzma = ["ruffle_core/lzma"]

# web features
canvas = ["ruffle_render_canvas"]
webgl = ["ruffle_render_webgl"]
webgpu = ["ruffle_render_wgpu"]
wgpu-webgl = ["ruffle_render_wgpu", "ruffle_render_wgpu/webgl"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = { version = "0.2", optional = true }
generational-arena = "0.2.8"
js-sys = "0.3.60"
log = { version = "0.4", features = ["serde"] }
ruffle_render_canvas = { path = "../render/canvas", optional = true }
ruffle_web_common = { path = "common" }
ruffle_render_webgl = { path = "../render/webgl", optional = true }
ruffle_render_wgpu = { path = "../render/wgpu", optional = true }
ruffle_video_software = { path = "../video/software" }
url = "2.3.1"
wasm-bindgen = "=0.2.83"
wasm-bindgen-futures = "0.4.33"
serde-wasm-bindgen = "0.4.5"
chrono = { version = "0.4", default-features = false, features = ["wasmbind", "clock"] }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0"
base64 = "0.13.1"

[dependencies.ruffle_core]
path = "../core"
default-features = false
features = ["audio", "nellymoser", "symphonia", "wasm-bindgen"]

[dependencies.web-sys]
version = "0.3.60"
features = [
    "AddEventListenerOptions", "AudioBuffer", "AudioBufferSourceNode", "AudioContext", "AudioDestinationNode",
    "AudioNode", "AudioParam", "Blob", "BlobPropertyBag", "ChannelMergerNode",
    "ChannelSplitterNode", "Element", "Event", "EventTarget", "GainNode", "HtmlCanvasElement",
    "HtmlElement", "HtmlFormElement", "KeyboardEvent", "Location", "PointerEvent", "Request", "RequestInit", "Response",
    "Storage", "WheelEvent", "Window",
]
